### ISSUE TITLE
Require symbols for JP ROMs for new Pull Requests

### ISSUE THREAD

**Issue by theCapypara** [UsernameFodder/pmdsky-debug#176]
**Is your feature request related to a problem? Please describe.**
At the moment a vast amount of symbols (and patches, but that's outside the scope of this repo) are only available for the US/NA and EU ROMs.

**Describe the solution you'd like**
I think with the recent contribution through #175 we should aim to update more symbols to have JP addresses and require future contributions to have JP symbols.

**Describe alternatives you've considered**
- We could do nothing, but this would probably eventually lead to issues of the JP ROMs being barely supported by projects using pmdsky-debug.
- We could incentivize contributors by adding it to the PR template (which doesn't exist yet) as a soft requirement

**Additional recommendations**
- A Pull Request description template should be created
- A document describing contribution should be added (unless there is already one and I'm just blind)

**Comment by UsernameFodder** [comment]
This seems kind of counter to a core design goal of the repo and `resymgen`, which is to encourage "just add what you have" contributions. When most people do research, they're usually only looking at one version at a time. There's already plenty of symbols in the repo that are NA-only or EU-only.

I think it's better to have incomplete information than no information at all. If there were a requirement that contributions must be multi-version, it would be pretty stifling. If there are symbols we really care about that aren't addressed in all versions, people are welcome to make pull requests that add them, and having the symbols in other version even helps with that by enabling cross-referencing.

> We could do nothing, but this would probably eventually lead to issues of the JP ROMs being barely supported by projects using pmdsky-debug.

IMO this isn't really in the scope of pmdsky-debug. This repo just provides all the information that's known. Verifying whether or not the JP offsets are present is a matter that ought to be up to users of the symbols tables.

> A document describing contribution should be added (unless there is already one and I'm just blind)

[There are already is one](https://github.com/UsernameFodder/pmdsky-debug/blob/master/docs/contributing.md).
