### ISSUE TITLE
Support per-version C headers

### ISSUE THREAD

**Issue by UsernameFodder** [UsernameFodder/pmdsky-debug#182]
**Is your feature request related to a problem? Please describe.**
@Adex-8x found that `struct monster` in the JP version doesn't have all the fields that exist in NA/EU. JP is missing:

- `in_action`
- `field_0x64`
- `field_0x65`
- `field_0x66`

With version-specific enums like `enum script_level_id*` and `enum script_object_id*`, the headers just define version-specific enum tags, e.g., `enum script_level_id_eu`. This is already somewhat unideal, and with `struct monster`, this approach will be cumbersome since `struct monster` is itself embedded in other structs like `struct dungeon`, so version differences would be "contagious".

We should figure out a good way to represent version differences that doesn't make the headers harder to use (e.g., importing in Ghidra).

**Describe the solution you'd like**
It would probably work to use `#define VERSION` in tandem with `#if` or something, and deal with conditional struct fields at the preprocessor level. This would require `#define`'ing the version before importing the headers. We could ship wrappers around the main `pmdsky.h` that define the variable for different game versions, and have people pick the one they want when importing. That way, you could still just import a single header into Ghidra.

By default, `pmdsky.h` should set the version to NA or EU if not defined, for compatibility.

Right now the headers shipped aren't version-specific, so in the release package, we would probably make separate copies of `pmdsky.h` and place them next to the already version-specific symbols.

**Comment by Adex-8x** [comment]
Adding onto this, I'm fairly certain there's also differences in `struct dungeon`. I don't know the exact details of it right now, but while investigating some more symbols, I found that the NA version at one point had:
```
0x022F7298: ldrb r0,[r0,#0xda] ; NA
```
While the JP version's equivalent had:
```
0x022F8864: ldrb r0,[r0,#0x36] ; JP
```
The code surrounding both these lines were otherwise identical.
