### ISSUE TITLE
Resymgen merge does not skip symbols out of range unless the version is NA

### ISSUE THREAD

**Issue by Metalcape** [UsernameFodder/pmdsky-debug#38]
When merging symbols from a CSV file, if I use the option `-v EU` then resymgen adds all symbols to the file, even if they are outside the address range of the block. This does not happen with `-v NA`.  I noticed that if I manually edit the `versions` field of the YAML file and put EU at the top, then it filters out symbols correctly. I also tried it with `-v JP` and it also does not work correctly.

**To reproduce**
This is the exact command I used (working directory is pmdsky-debug/symbols):
```
resymgen merge -x -f csv -v EU -i ../../symbol_table_eu.csv overlay29.yml
```
I've also tested it on arm9.yml and overlay10.yml, with the same results.

**Expected behavior**
Symbols outside the address range of the block should be filtered out automatically.

**Desktop environment**
 - Windows 10
 - Tested both in the WSL terminal and Powershell, and it behaves the same

**Additional context**
These are the CSV files I was trying to merge:
- [symbol_table_na.csv](https://github.com/UsernameFodder/pmdsky-debug/files/8653949/symbol_table_na.csv)
- [symbol_table_eu.csv](https://github.com/UsernameFodder/pmdsky-debug/files/8653950/symbol_table_eu.csv)

**Comment by UsernameFodder** [comment]
Thanks for pointing this out, this is due to an unfortunate bit of complexity in the implementation that came back to bite, apparently.
