### ISSUE TITLE
Auto-generated Changelog for Symbol Updates

### ISSUE THREAD

**Issue by theCapypara** [UsernameFodder/pmdsky-debug#58]
**Is your feature request related to a problem? Please describe.**
At the moment when updating libraries that use pmdsky-debug such as SkyTemple Files and (to a lesser extend) c-of-time/Rust of Darkness, it's a bit of a "guessing game" / going through the history to see what symbols have changed and what might break. With SkyTemple it's especially problematic due to the lack of options for static analysis (though that's probably also that could be improved over there). SkyTemple does have some tests that check for some symbols, but they aren't really 100% reliable for this...

**Describe the solution you'd like**
It would be great if there was a changelog with each release that outlined the renamed / removed / added / updated symbols. Ideally this would *not* (just) be in the Github releases, since they are very inconvenient to get an overview of changes over multiple releases.

**Describe alternatives you've considered**
- Doing nothing; just relying on external libs to do checks themselves
- Doing this manually (not practical)

**Additional context**
/

**Comment by UsernameFodder** [comment]
I don't know about keeping a change-log outside of the releases, e.g., committed in the repo. I don't think that's very scalable, and it'd get pretty big over time unless there was some sort of expiration period. It'd also create a lot of commit churn.

Maybe a good solution would be to create a script in `tools/` that can generate a symbol diff based on the Git history, similar to `git diff`. I think that could be pretty doable, although I'd have to experiment.

**Comment by UsernameFodder** [comment]
@theCapypara Is this still going to be useful for you now that [pmdsky-debug-py](https://github.com/SkyTemple/pmdsky-debug-py) exists? I've given this some thought and I think it's possible, but implementation will be a tad involved (my current idea involves [maximum cardinality matching](https://en.wikipedia.org/wiki/Maximum_cardinality_matching)). Not crazy difficult, but I'd rather not do it if it's already been rendered obsolete by pmdsky-debug-py.

Another built-in alternative is to just run `git diff` on specific file(s) within `symbols/`, right? I suppose it's a bit harder to read and not very automation-friendly though.

**Comment by theCapypara** [comment]
I personally don't need it anymore now, just for c-of-time but that's always a manual process anyway. 

I still think having something would be good though in general. Maybe a little shell script that does option #2 with resymgen?

**Comment by UsernameFodder** [comment]
I couldn't stop thinking about the diffing algorithm I dreamed up, so I decided to just implement the full thing :P. Maybe it'll still be useful at some point.
